### ISSUE TITLE
Package "@ns3/nx-serverless" has no builders defined

### ISSUE THREAD

**Issue by lylejohnson** [Bielik20/nx-plugins#89]
I'm attempting an upgrade of my monorepo from Nx 14 to Nx 15. There are a number of lambda function based projects that built and deployed just fine under Nx 14, but under Nx 15 I'm seeing this error message when I run the "deploy" target:
```
$ nx run spog-auth-token-generator:deploy --stage=development

...

>  NX   Package "@ns3/nx-serverless" has no builders defined.

   Pass --verbose to see the stacktrace.
```
The stack trace doesn't provide much more information:
```
Error: Package "@ns3/nx-serverless" has no builders defined.
    at WorkspaceNodeModulesArchitectHost.resolveBuilder (/Users/ljohnson/src/lighting/simplysnap-omni/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:124:19)
    at ArchitectTargetJobRegistry._resolveBuilder (/Users/ljohnson/src/lighting/simplysnap-omni/node_modules/@angular-devkit/architect/src/architect.js:101:54)
    at MergeMapSubscriber.project (/Users/ljohnson/src/lighting/simplysnap-omni/node_modules/@angular-devkit/architect/src/architect.js:161:25)
    at MergeMapSubscriber._tryNext (/Users/ljohnson/src/lighting/simplysnap-omni/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/Users/ljohnson/src/lighting/simplysnap-omni/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at Subscriber.next (/Users/ljohnson/src/lighting/simplysnap-omni/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:66:18)
    at /Users/ljohnson/src/lighting/simplysnap-omni/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/util/subscribeToPromise.js:7:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Bielik20** [comment]
The newest version of this plugin is for Nx 16, so you may need to try older version or update to Nx 16

**Comment by lylejohnson** [comment]
@Bielik20 Thank you. I downgraded to version 3.8.0 of the plugin and that's working for me.
